name: tests

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

# Cancel previous running if a new push is made
# Source: https://stackoverflow.com/a/72408109/123545
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker on macOS
        id: setup-docker
        uses: douglascamata/setup-docker-macos-action@v1.0.2
        with:
          lima: v1.2.1
          colima: v0.9.1
          colima-network-address: false

      - name: Run Typesense
        run: |
          mkdir $(pwd)/typesense-data
          docker run -p 8108:8108 \
            -d \
            -v$(pwd)/typesense-data:/data typesense/typesense:30.0.rca34 \
            --data-dir /data \
            --api-key=xyz \
            --enable-cors \
            --enable-search-analytics=true \
            --analytics-dir=/analytics-data
        shell: bash

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: swift test
