name: tests
on: [push, pull_request]

# Cancel previous running if a new push is made
# Source: https://stackoverflow.com/a/72408109/123545
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and start dependencies
        run: |
          brew install docker
          # https://github.com/abiosoft/colima/issues/424#issuecomment-1335912905
          colima delete
          colima start --arch x86_64

      - name: Run Typesense
        run: |
          mkdir $(pwd)/typesense-data
          docker run -p 8108:8108 \
            -d \
            -v$(pwd)/typesense-data:/data typesense/typesense:0.25.2 \
            --data-dir /data \
            --api-key=xyz \
            --enable-cors
        shell: bash

      - name: Set up Xcode 13.2.1
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: '13.2.1'

      - name: Run Tests
        run: swift test
